### ISSUE TITLE
Text missing when using --image-preview flag

### ISSUE THREAD

**Issue by HaruNashii** [anotherlusitano/vizer-cli#13]
when using the --image-preview flag all the texts like 
("Total of episodes to watch:", "Select the episode you want watch:". "Total of media to watch:", "Select what you want to watch:")
doesn't appear on the screen

**without the --image-preview flag**
![image](https://github.com/anotherlusitano/vizer-cli/assets/116776134/03f53a8f-8001-4bb6-b459-d435ac34334e)
**with the --image-preview flag**
![image](https://github.com/anotherlusitano/vizer-cli/assets/116776134/7bc66ca8-5816-453e-b60c-bd20904047f4)

**Comment by anotherlusitano** [comment]
Will be easier if the #11 is merged, so I will wait.
