### ISSUE TITLE
[SUGGESTION] set a "experimental" warning to the geckodriver flag in the help page

### ISSUE THREAD

**Issue by HaruNashii** [anotherlusitano/vizer-cli#40]
as the geckodriver is extremely unstable, i think it would be nice to give a little warning in the --help page saying that the geckodriver support is still in stage of tests

this warning could be shown in the description per example.

OBS:
the proposed change in the [#33](https://github.com/anotherlusitano/vizer-cli/issues/33), may solve the instability of the geckokdriver,

**Comment by anotherlusitano** [comment]
Now that #43 has been merged, we can consider this issue solved, even if the geckodriver has some warnings and errors, it doesn't break the flow of the app by suppressing the errors. The errors are from fantoccini and I'll fix them soon with some refactoring in the code by modifying the way the program gets the video url.
