### ISSUE TITLE
the application does not start again if the application was not properly closed (only if using the image preview feature)

### ISSUE THREAD

**Issue by HaruNashii** [anotherlusitano/vizer-cli#7]
if you kill the "vizer-cli" (by closing the terminal or via one task manager) while is in the choose media screen with the "--image-preview" flag enabled, the app won't open again if you try to open with the flag "--image-preview", due to the app trying to create the temporary folder for the "image preview" that already was created previously.

to fix this issue you can make the function create_temp_dir() [located in "src/fs/temp_dir.rs"] only create the folder if the folder doesn't already exist.

**you can do this with the std::path; crate**

**example:**  
```
use std::path::Path;

fn example_fn()
{
         if !Path::new("/path/to/folder").exists()
         {
                   // Do One Action If The Folder Doesn't Exist
         }
}
```

**Comment by anotherlusitano** [comment]
Thank you :)
